% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={PS4 Spatial},
  pdfauthor={Claudia Felipe and Francesca Leon},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{PS4 Spatial}
\author{Claudia Felipe and Francesca Leon}
\date{}

\begin{document}
\maketitle

\RecustomVerbatimEnvironment{verbatim}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaksymbolleft={},
  breaklines
}


\textbf{PS4:} Due Sat Nov 2 at 5:00PM Central. Worth 100 points.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  This problem set is a paired problem set.
\item
  Play paper, scissors, rock to determine who goes first. Call that
  person Partner 1. • Partner 1 (name and cnet ID): Francesca Leon
  (francescaleon) • Partner 2 (name and cnet ID): Claudia Felipe
  (claudiafelipe)
\item
  Partner 1 will accept the ps4 and then share the link it creates with
  their partner. You can only share it with one partner so you will not
  be able to change it after your partner has accepted.
\item
  ``This submission is our work alone and complies with the 30538
  integrity policy.'' Add your initials to indicate your agreement:
  \textbf{CF} \textbf{FL}
\item
  ``I have uploaded the names of anyone else other than my partner and I
  worked with on the problem set here'' (1 point)
\item
  Late coins used this pset: \textbf{0} Late coins left after
  submission: \textbf{4}
\end{enumerate}

\subsection{Style Points (10 pts)}\label{style-points-10-pts}

\subsection{Submission Steps (10 pts)}\label{submission-steps-10-pts}

\subsection{Download and explore the Provider of Services (POS) file (10
pts)}\label{download-and-explore-the-provider-of-services-pos-file-10-pts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The variables I pulled are: PRVDR\_CTGRY\_SBTYP\_CD, PRVDR\_CTGRY\_CD,
  FAC\_NAME, PRVDR\_NUM, STATE\_CD, PGM\_TRMNTN\_CD, ZIP\_CD.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ pandas }\ImportTok{as}\NormalTok{ pd}
\ImportTok{import}\NormalTok{ altair }\ImportTok{as}\NormalTok{ alt}
\ImportTok{import}\NormalTok{ time}
\ImportTok{import}\NormalTok{ numpy }\ImportTok{as}\NormalTok{ np}
\ImportTok{import}\NormalTok{ warnings}
\ImportTok{import}\NormalTok{ geopandas }\ImportTok{as}\NormalTok{ gpd}
\ImportTok{import}\NormalTok{ os}
\ImportTok{import}\NormalTok{ matplotlib.pyplot }\ImportTok{as}\NormalTok{ plt}
\ImportTok{import}\NormalTok{ yaml}

\NormalTok{warnings.filterwarnings(}\StringTok{\textquotesingle{}ignore\textquotesingle{}}\NormalTok{)}
\NormalTok{alt.renderers.enable(}\StringTok{\textquotesingle{}png\textquotesingle{}}\NormalTok{)}
\NormalTok{alt.data\_transformers.disable\_max\_rows()}

\NormalTok{base\_directory }\OperatorTok{=} \StringTok{\textquotesingle{}/Users/francescaleon/Documents/GitHub/DAPII/problem{-}set{-}4{-}fran{-}clau/\textquotesingle{}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\hfill\break
a. The number of hospitals reported are 7,245. This number doesn't make
full sense because seems to be too high.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pos2016 }\OperatorTok{=}\NormalTok{ pd.read\_csv(os.path.join(base\_directory, }\StringTok{\textquotesingle{}pos2016.csv\textquotesingle{}}\NormalTok{))}
\NormalTok{pos2016 }\OperatorTok{=}\NormalTok{ pos2016[(pos2016[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (pos2016[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_SBTYP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{)]}
\NormalTok{pos2016[}\StringTok{\textquotesingle{}year\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \DecValTok{2016}

\NormalTok{pos2016[}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].nunique()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
7245
\end{verbatim}

\hfill\break
b. Based on the American Hospital Association Statistics, the number of
short term hospitals in 2018 (oldest available report) was 4,840. This
number differs significantly from the number calculated using the
database (7,245). This could happen because the hospitals are mistakenly
categorized as short-term in the database. Another explanation could be
that some of the short-term hospitals are closed but still appear in the
database.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pos2017 }\OperatorTok{=}\NormalTok{ pd.read\_csv(os.path.join(base\_directory, }\StringTok{\textquotesingle{}pos2017.csv\textquotesingle{}}\NormalTok{))}
\NormalTok{pos2017 }\OperatorTok{=}\NormalTok{ pos2017[(pos2017[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (pos2017[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_SBTYP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{)]}
\NormalTok{pos2017[}\StringTok{\textquotesingle{}year\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \DecValTok{2017}

\NormalTok{pos2018 }\OperatorTok{=}\NormalTok{ pd.read\_csv(os.path.join(base\_directory, }\StringTok{\textquotesingle{}pos2018.csv\textquotesingle{}}\NormalTok{), encoding}\OperatorTok{=}\StringTok{"ISO{-}8859{-}1"}\NormalTok{)}
\NormalTok{pos2018 }\OperatorTok{=}\NormalTok{ pos2018[(pos2018[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (pos2018[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_SBTYP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{)]}
\NormalTok{pos2018[}\StringTok{\textquotesingle{}year\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \DecValTok{2018}

\NormalTok{pos2019 }\OperatorTok{=}\NormalTok{ pd.read\_csv(os.path.join(base\_directory, }\StringTok{\textquotesingle{}pos2019.csv\textquotesingle{}}\NormalTok{), encoding}\OperatorTok{=}\StringTok{"ISO{-}8859{-}1"}\NormalTok{)}
\NormalTok{pos2019 }\OperatorTok{=}\NormalTok{ pos2019[(pos2019[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (pos2019[}\StringTok{\textquotesingle{}PRVDR\_CTGRY\_SBTYP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{==}\DecValTok{1}\NormalTok{)]}
\NormalTok{pos2019[}\StringTok{\textquotesingle{}year\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \DecValTok{2019}

\NormalTok{pos }\OperatorTok{=}\NormalTok{ pd.concat([pos2016, pos2017, pos2018, pos2019], ignore\_index}\OperatorTok{=}\VariableTok{True}\NormalTok{)}


\NormalTok{alt.Chart(pos, title }\OperatorTok{=} \StringTok{\textquotesingle{}Number of Observations per Year\textquotesingle{}}\NormalTok{).mark\_bar().encode(}
\NormalTok{  alt.X(}\StringTok{\textquotesingle{}year:O\textquotesingle{}}\NormalTok{).title(}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{),}
\NormalTok{  alt.Y(}\StringTok{\textquotesingle{}count():Q\textquotesingle{}}\NormalTok{).title(}\StringTok{\textquotesingle{}Number of Observations\textquotesingle{}}\NormalTok{)}
\NormalTok{).properties(width }\OperatorTok{=} \DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-4-output-1.png}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\hfill\break
a.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alt.Chart(pos, title }\OperatorTok{=} \StringTok{\textquotesingle{}Number of Unique Hospitals per Year\textquotesingle{}}\NormalTok{).mark\_bar().encode(}
\NormalTok{  alt.X(}\StringTok{\textquotesingle{}year:O\textquotesingle{}}\NormalTok{).title(}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{),}
\NormalTok{  alt.Y(}\StringTok{\textquotesingle{}distinct(PRVDR\_NUM):Q\textquotesingle{}}\NormalTok{).title(}\StringTok{\textquotesingle{}Number of Unique Hospitals\textquotesingle{}}\NormalTok{)}
\NormalTok{).properties(width }\OperatorTok{=} \DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-5-output-1.png}

\hfill\break
b. The graphs are the same, with the same numbers. This means that the
database contains the same number of observations and unique hospitals.
This tells that the structure of the data is attached to the unique
hospitals, those being the unit of observation.

\subsection{Identify hospital closures in POS file (15 pts)
(*)}\label{identify-hospital-closures-in-pos-file-15-pts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The total suspected hospital closures is 174.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filter active hospitals in 2016}
\NormalTok{active\_2016 }\OperatorTok{=}\NormalTok{ pos2016[pos2016[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{][[}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]]}

\CommentTok{\# Create a list to store the suspected closure year}
\NormalTok{closure\_data }\OperatorTok{=}\NormalTok{ []}

\CommentTok{\# Iterate over each hospital active in 2016 and check if it remains active in the following years}
\ControlFlowTok{for}\NormalTok{ \_, row }\KeywordTok{in}\NormalTok{ active\_2016.iterrows():}
\NormalTok{    provider\_id }\OperatorTok{=}\NormalTok{ row[}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{]}
\NormalTok{    facility\_name }\OperatorTok{=}\NormalTok{ row[}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{]}
\NormalTok{    zip\_code }\OperatorTok{=}\NormalTok{ row[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]}
    
    \CommentTok{\# Check each successive year}
    \ControlFlowTok{if}\NormalTok{ provider\_id }\KeywordTok{not} \KeywordTok{in}\NormalTok{ pos2017[pos2017[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{][}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].values:}
\NormalTok{        closure\_data.append([facility\_name, zip\_code, }\DecValTok{2017}\NormalTok{])}
    \ControlFlowTok{elif}\NormalTok{ provider\_id }\KeywordTok{not} \KeywordTok{in}\NormalTok{ pos2018[pos2018[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{][}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].values:}
\NormalTok{        closure\_data.append([facility\_name, zip\_code, }\DecValTok{2018}\NormalTok{])}
    \ControlFlowTok{elif}\NormalTok{ provider\_id }\KeywordTok{not} \KeywordTok{in}\NormalTok{ pos2019[pos2019[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{][}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].values:}
\NormalTok{        closure\_data.append([facility\_name, zip\_code, }\DecValTok{2019}\NormalTok{])}

\CommentTok{\# Convert the results into a DataFrame}
\NormalTok{closure\_df }\OperatorTok{=}\NormalTok{ pd.DataFrame(closure\_data, columns}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{])}

\BuiltInTok{print}\NormalTok{(}\StringTok{"Total suspected hospital closures:"}\NormalTok{, closure\_df.shape[}\DecValTok{0}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Total suspected hospital closures: 174
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sort hospitals by name and select the first 10 rows}
\NormalTok{sorted\_hospitals }\OperatorTok{=}\NormalTok{ closure\_df.sort\_values(by}\OperatorTok{=}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{)[[}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{]].head(}\DecValTok{10}\NormalTok{)}

\CommentTok{\# Display the results}
\NormalTok{sorted\_hospitals.style.hide()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{}\label{T_3f5ca}\tabularnewline
\toprule\noalign{}
FAC\_NAME & Year of Susp. Closure \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
FAC\_NAME & Year of Susp. Closure \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ABRAZO MARYVALE CAMPUS & 2017 \\
ADVENTIST MEDICAL CENTER - CENTRAL VALLEY & 2017 \\
AFFINITY MEDICAL CENTER & 2018 \\
ALBANY MEDICAL CENTER / SOUTH CLINICAL CAMPUS & 2017 \\
ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE & 2017 \\
ALLIANCE LAIRD HOSPITAL & 2019 \\
ALLIANCEHEALTH DEACONESS & 2019 \\
ANNE BATES LEACH EYE HOSPITAL & 2019 \\
ARKANSAS VALLEY REGIONAL MEDICAL CENTER & 2017 \\
BANNER CHURCHILL COMMUNITY HOSPITAL & 2017 \\
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Count the total number of active hospitals by ZIP code for each year}
\NormalTok{active\_by\_zip\_2016 }\OperatorTok{=}\NormalTok{ pos2016[pos2016[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{].groupby(}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{).size().to\_dict()}
\NormalTok{active\_by\_zip\_2017 }\OperatorTok{=}\NormalTok{ pos2017[pos2017[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{].groupby(}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{).size().to\_dict()}
\NormalTok{active\_by\_zip\_2018 }\OperatorTok{=}\NormalTok{ pos2018[pos2018[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{].groupby(}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{).size().to\_dict()}
\NormalTok{active\_by\_zip\_2019 }\OperatorTok{=}\NormalTok{ pos2019[pos2019[}\StringTok{\textquotesingle{}PGM\_TRMNTN\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{0}\NormalTok{].groupby(}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{).size().to\_dict()}

\CommentTok{\# Create a DataFrame from the dictionaries}
\NormalTok{active\_counts\_df }\OperatorTok{=}\NormalTok{ pd.DataFrame(\{}
    \StringTok{\textquotesingle{}2016\textquotesingle{}}\NormalTok{: pd.Series(active\_by\_zip\_2016),}
    \StringTok{\textquotesingle{}2017\textquotesingle{}}\NormalTok{: pd.Series(active\_by\_zip\_2017),}
    \StringTok{\textquotesingle{}2018\textquotesingle{}}\NormalTok{: pd.Series(active\_by\_zip\_2018),}
    \StringTok{\textquotesingle{}2019\textquotesingle{}}\NormalTok{: pd.Series(active\_by\_zip\_2019)}
\NormalTok{\})}

\CommentTok{\# Fill any missing values with 0, in case a ZIP code has no active hospitals in a given year}
\NormalTok{active\_counts\_df }\OperatorTok{=}\NormalTok{ active\_counts\_df.fillna(}\DecValTok{0}\NormalTok{).astype(}\BuiltInTok{int}\NormalTok{)}

\CommentTok{\# Create new columns for the difference in active hospital counts between consecutive years}
\NormalTok{active\_counts\_df[}\StringTok{\textquotesingle{}2017{-}2016\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2017\textquotesingle{}}\NormalTok{] }\OperatorTok{{-}}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2016\textquotesingle{}}\NormalTok{]}
\NormalTok{active\_counts\_df[}\StringTok{\textquotesingle{}2018{-}2017\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2018\textquotesingle{}}\NormalTok{] }\OperatorTok{{-}}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2017\textquotesingle{}}\NormalTok{]}
\NormalTok{active\_counts\_df[}\StringTok{\textquotesingle{}2019{-}2018\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2019\textquotesingle{}}\NormalTok{] }\OperatorTok{{-}}\NormalTok{ active\_counts\_df[}\StringTok{\textquotesingle{}2018\textquotesingle{}}\NormalTok{]}

\NormalTok{active\_counts\_df }\OperatorTok{=}\NormalTok{ active\_counts\_df.reset\_index()}
\NormalTok{active\_counts\_df }\OperatorTok{=}\NormalTok{ active\_counts\_df.rename(columns}\OperatorTok{=}\NormalTok{\{}\StringTok{\textquotesingle{}index\textquotesingle{}}\NormalTok{: }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{\})}

\CommentTok{\# Perform the merge on \textquotesingle{}ZIP\_CD\textquotesingle{}}
\NormalTok{merged\_df }\OperatorTok{=}\NormalTok{ pd.merge(closure\_df, active\_counts\_df, on}\OperatorTok{=}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{, how}\OperatorTok{=}\StringTok{\textquotesingle{}left\textquotesingle{}}\NormalTok{)}

\CommentTok{\#}
\NormalTok{merged\_df[}\StringTok{\textquotesingle{}change\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ np.where(}
\NormalTok{    merged\_df[}\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{2017}\NormalTok{, merged\_df[}\StringTok{\textquotesingle{}2017{-}2016\textquotesingle{}}\NormalTok{],}
\NormalTok{    np.where(}
\NormalTok{        merged\_df[}\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{2018}\NormalTok{, merged\_df[}\StringTok{\textquotesingle{}2018{-}2017\textquotesingle{}}\NormalTok{],}
\NormalTok{        np.where(}
\NormalTok{            merged\_df[}\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{] }\OperatorTok{==} \DecValTok{2019}\NormalTok{, merged\_df[}\StringTok{\textquotesingle{}2019{-}2018\textquotesingle{}}\NormalTok{],}
\NormalTok{            np.nan  }
\NormalTok{        )}
\NormalTok{    )}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  The number of hospitals potentially merged/acquired is 8
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Possible mergers or acquisitions: hospitals with "change" \textless{}= 0}
\NormalTok{merged\_or\_acquisition }\OperatorTok{=}\NormalTok{ merged\_df[(merged\_df[}\StringTok{\textquotesingle{}change\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{0}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (merged\_df[}\StringTok{\textquotesingle{}change\textquotesingle{}}\NormalTok{].notna())]}
\NormalTok{n\_merged }\OperatorTok{=}\NormalTok{ merged\_or\_acquisition.shape[}\DecValTok{0}\NormalTok{]}
\BuiltInTok{print}\NormalTok{(}\StringTok{"Number of hospitals potentially merged/acquired:"}\NormalTok{, n\_merged)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Number of hospitals potentially merged/acquired: 8
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remaining valid closures with "change" \textgreater{}= 1}
\NormalTok{df\_corrected }\OperatorTok{=}\NormalTok{ merged\_df[(merged\_df[}\StringTok{\textquotesingle{}change\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}} \DecValTok{0}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (merged\_df[}\StringTok{\textquotesingle{}change\textquotesingle{}}\NormalTok{].notna())]}
\BuiltInTok{print}\NormalTok{(}\StringTok{"Remaining valid closures after excluding mergers/acquisitions:"}\NormalTok{, df\_corrected.shape[}\DecValTok{0}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Remaining valid closures after excluding mergers/acquisitions: 166
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The remaining valid closures after excluding mergers/acquisitions is
  166.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sort the corrected DataFrame by hospital name and display the first 10 rows}

\NormalTok{sorted\_corrected\_closures }\OperatorTok{=}\NormalTok{ df\_corrected.sort\_values(by}\OperatorTok{=}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{)[[}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{]].head(}\DecValTok{10}\NormalTok{)}
\NormalTok{sorted\_corrected\_closures[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{=}\NormalTok{sorted\_corrected\_closures[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]}\OperatorTok{\textbackslash{}}
\NormalTok{    .astype(}\BuiltInTok{int}\NormalTok{)}
\NormalTok{sorted\_corrected\_closures.style.hide()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lll@{}}
\caption{}\label{T_1bb30}\tabularnewline
\toprule\noalign{}
FAC\_NAME & ZIP\_CD & Year of Susp. Closure \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
FAC\_NAME & ZIP\_CD & Year of Susp. Closure \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ABRAZO MARYVALE CAMPUS & 85031 & 2017 \\
ADVENTIST MEDICAL CENTER - CENTRAL VALLEY & 93230 & 2017 \\
AFFINITY MEDICAL CENTER & 44646 & 2018 \\
ALBANY MEDICAL CENTER / SOUTH CLINICAL CAMPUS & 12208 & 2017 \\
ALLEGIANCE SPECIALTY HOSPITAL OF KILGORE & 75662 & 2017 \\
ALLIANCE LAIRD HOSPITAL & 39365 & 2019 \\
ALLIANCEHEALTH DEACONESS & 73112 & 2019 \\
ANNE BATES LEACH EYE HOSPITAL & 33136 & 2019 \\
ARKANSAS VALLEY REGIONAL MEDICAL CENTER & 81050 & 2017 \\
BANNER CHURCHILL COMMUNITY HOSPITAL & 89406 & 2017 \\
\end{longtable}

\subsection{Download Census zip code shapefile (10
pt)}\label{download-census-zip-code-shapefile-10-pt}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
\end{enumerate}

\hfill\break
a. The types of files are:\\
- .shp (shapefile): This file stores the geometric data representing the
shape of geographic features.\\
- .shx (shape index file): This file contains an index of the geometry
data in the .shp file, allowing for faster spatial queries and access.\\
- .dbf (database file): This file stores attribute data in a tabular
format, where each row represents a feature, and columns contain the
attributes or properties of that feature.\\
- .prj (projection file): This file contains information about the
coordinate system and projection used, allowing the data to be correctly
placed on a map.\\
- .xml (metadata file): This file contains metadata about the shapefile,
such as the data source, description, and any relevant metadata
standards used.

\hfill\break
b. The databases have different sizes:\\
- .shp (shapefile): 837.5 MB\\
- .shx (shape index file): 265 KB\\
- .dbf (database file): 6.4 MB\\
- .prj (projection file): 165 bytes\\
- .xml (metadata file): 16 KB\\

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Load shapefile}
\NormalTok{all\_shp }\OperatorTok{=}\NormalTok{ gpd.read\_file(os.path.join(base\_directory, }\StringTok{\textquotesingle{}gz\_2010\_us\_860\_00\_500k/gz\_2010\_us\_860\_00\_500k.shp\textquotesingle{}}\NormalTok{))}
\NormalTok{all\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ all\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].astype(}\BuiltInTok{int}\NormalTok{)}

\CommentTok{\#Filter shapefile to Texas zipcodes}
\NormalTok{texas\_shp }\OperatorTok{=}\NormalTok{ all\_shp[(all\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{75000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (all\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{79900}\NormalTok{)]}

\CommentTok{\#Merge shapefile with hospitals database 2016}
\NormalTok{hospitals\_texas\_2016 }\OperatorTok{=}\NormalTok{ pd.merge(texas\_shp, pos2016, left\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{], right\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{], how}\OperatorTok{=}\StringTok{\textquotesingle{}left\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Calculate number of hospitals per zipcode in 2016}
\NormalTok{hospitals\_texas\_2016 }\OperatorTok{=}\NormalTok{ hospitals\_texas\_2016.groupby(}\StringTok{\textquotesingle{}geometry\textquotesingle{}}\NormalTok{)}\OperatorTok{\textbackslash{}}
\NormalTok{    .count()[}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].reset\_index()}

\CommentTok{\#Plot choropleth }
\NormalTok{hospitals\_texas\_2016 }\OperatorTok{=}\NormalTok{ gpd.GeoDataFrame(hospitals\_texas\_2016, geometry}\OperatorTok{=}\StringTok{\textquotesingle{}geometry\textquotesingle{}}\NormalTok{)}
\NormalTok{hosp\_texas }\OperatorTok{=}\NormalTok{ hospitals\_texas\_2016.plot(column}\OperatorTok{=}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{, cmap}\OperatorTok{=}\StringTok{\textquotesingle{}YlGnBu\textquotesingle{}}\NormalTok{, legend}\OperatorTok{=}\VariableTok{True}\NormalTok{)}
\NormalTok{plt.gcf().set\_size\_inches(}\DecValTok{8}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{hosp\_texas.set\_title(}\StringTok{"Number of Hospitals by ZIP Code"}\NormalTok{, fontsize}\OperatorTok{=}\DecValTok{15}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-12-output-1.pdf}

\subsection{Calculate zip code's distance to the nearest hospital (20
pts)
(*)}\label{calculate-zip-codes-distance-to-the-nearest-hospital-20-pts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The resulting GeoDataFrame has dimensions (33120, 3), where 33120 is
  the number of unique zip codes in the dataset and 2 is the number of
  columns. The 3 columns are:\\
\end{enumerate}

\begin{itemize}
\tightlist
\item
  ZCTA5: This column contains a unique zip code.\\
\item
  centroid: This is a point geometry column that represents the centroid
  of each zip code area, containing the latitude and longitude.\\
\item
  geometry: Represents an area enclosed by a series of connected lines
  that form a closed loop.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Get zipcode centroid and create GeoDataFrame}
\NormalTok{all\_shp[}\StringTok{\textquotesingle{}centroid\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ all\_shp.geometry.centroid}
\NormalTok{zips\_all\_centroids }\OperatorTok{=}\NormalTok{ gpd.GeoDataFrame(all\_shp[[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}centroid\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}geometry\textquotesingle{}}\NormalTok{]], geometry}\OperatorTok{=}\StringTok{\textquotesingle{}centroid\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The number of unique zipcodes in `zips\_texas\_centroids' is 1,910 and
  in~`zips\_texas\_borderstates\_centroids' is 4,057.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Filter Texas centroids}
\NormalTok{zips\_texas\_centroids }\OperatorTok{=}\NormalTok{ zips\_all\_centroids[(zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{75000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{79900}\NormalTok{)]}

\CommentTok{\#Filter Texas and bordering states centroids}
\NormalTok{zips\_texas\_borderstates\_centroids }\OperatorTok{=}\NormalTok{ zips\_all\_centroids[}
\NormalTok{    ((zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{87000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{88499}\NormalTok{)) }\OperatorTok{|}
\NormalTok{    ((zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{73000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{74999}\NormalTok{)) }\OperatorTok{|}
\NormalTok{    ((zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{75000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{79999}\NormalTok{)) }\OperatorTok{|}
\NormalTok{    ((zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{71600}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{72999}\NormalTok{)) }\OperatorTok{|}
\NormalTok{    ((zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{70000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (zips\_all\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{71599}\NormalTok{))}
\NormalTok{]}

\CommentTok{\#Calculate number of unique hospitals}
\NormalTok{zips\_texas\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].nunique()}
\NormalTok{zips\_texas\_borderstates\_centroids[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].nunique()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
4057
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  I did a left merge using `zips\_texas\_borderstates\_centroids' and
  `pos2016' based on the variables `ZCTA5' and `ZIP\_CD' respectively.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Merge with hospitals database for 2016}
\NormalTok{zips\_withhospital\_centroids }\OperatorTok{=}\NormalTok{ pd.merge(zips\_texas\_borderstates\_centroids, pos2016, left\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{], right\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{], how}\OperatorTok{=}\StringTok{\textquotesingle{}left\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Calculate number of hospitals by zipcode}
\NormalTok{zips\_withhospital\_centroids }\OperatorTok{=}\NormalTok{ zips\_withhospital\_centroids.groupby([}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}centroid\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}geometry\textquotesingle{}}\NormalTok{]).count()[}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{].reset\_index().rename(columns}\OperatorTok{=}\NormalTok{\{}\StringTok{\textquotesingle{}PRVDR\_NUM\textquotesingle{}}\NormalTok{: }\StringTok{\textquotesingle{}num\_hospitals\textquotesingle{}}\NormalTok{\})}

\CommentTok{\#Filter zipcodes with at least 1 hospital}
\NormalTok{zips\_withhospital\_centroids }\OperatorTok{=}\NormalTok{ gpd.GeoDataFrame(zips\_withhospital\_centroids}\OperatorTok{\textbackslash{}}
\NormalTok{    [zips\_withhospital\_centroids[}\StringTok{\textquotesingle{}num\_hospitals\textquotesingle{}}\NormalTok{]}\OperatorTok{\textgreater{}}\DecValTok{0}\NormalTok{], geometry}\OperatorTok{=}\StringTok{\textquotesingle{}centroid\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\hfill\break
a.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Subset 10 zipcodes for Texas}
\NormalTok{zips\_texas\_centroids\_10 }\OperatorTok{=}\NormalTok{ zips\_texas\_centroids.head(}\DecValTok{10}\NormalTok{)}

\CommentTok{\#Run join to nearest zipcode with hospitals and calculate time for 10 zipcodes}
\NormalTok{st\_10 }\OperatorTok{=}\NormalTok{ time.time()}

\NormalTok{join\_nearest\_10 }\OperatorTok{=}\NormalTok{ gpd.sjoin\_nearest(zips\_texas\_centroids\_10, zips\_withhospital\_centroids, how}\OperatorTok{=}\StringTok{\textquotesingle{}inner\textquotesingle{}}\NormalTok{, distance\_col}\OperatorTok{=}\StringTok{"distance"}\NormalTok{)}

\NormalTok{et\_10 }\OperatorTok{=}\NormalTok{ time.time()}
\BuiltInTok{print}\NormalTok{(}\StringTok{\textquotesingle{}Execution time:\textquotesingle{}}\NormalTok{, et\_10 }\OperatorTok{{-}}\NormalTok{ st\_10, }\StringTok{\textquotesingle{}seconds\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Estimate total time}
\BuiltInTok{print}\NormalTok{(}\StringTok{\textquotesingle{}I calculate the entire processing time to be:\textquotesingle{}}\NormalTok{, (et\_10 }\OperatorTok{{-}}\NormalTok{ st\_10)}\OperatorTok{*}\DecValTok{191}\NormalTok{, }\StringTok{\textquotesingle{}seconds\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Execution time: 0.031552791595458984 seconds
I calculate the entire processing time to be: 6.026583194732666 seconds
\end{verbatim}

\hfill\break
b. My estimation was significantly higher than the real excution time
for the entire database.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Run join to nearest zipcode with hospitals and calculate time for entire dataset}
\NormalTok{st }\OperatorTok{=}\NormalTok{ time.time()}

\NormalTok{join\_nearest }\OperatorTok{=}\NormalTok{ gpd.sjoin\_nearest(zips\_texas\_centroids, zips\_withhospital\_centroids, how}\OperatorTok{=}\StringTok{\textquotesingle{}inner\textquotesingle{}}\NormalTok{, distance\_col}\OperatorTok{=}\StringTok{"distance"}\NormalTok{)}

\NormalTok{et }\OperatorTok{=}\NormalTok{ time.time()}
\BuiltInTok{print}\NormalTok{(}\StringTok{\textquotesingle{}Entire processing time:\textquotesingle{}}\NormalTok{, et }\OperatorTok{{-}}\NormalTok{ st, }\StringTok{\textquotesingle{}seconds\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Entire processing time: 0.020545005798339844 seconds
\end{verbatim}

\hfill\break
c.~The .prj file is in degrees (units).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Convert distance in degrees to miles using 1 degree = 69 miles}
\NormalTok{join\_nearest[}\StringTok{\textquotesingle{}distance\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ join\_nearest[}\StringTok{\textquotesingle{}distance\textquotesingle{}}\NormalTok{]}\OperatorTok{*}\DecValTok{69}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\hfill\break
a. The distance is in miles (units).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Calculate mean distance by zipcode}
\NormalTok{mean\_distance\_zip }\OperatorTok{=}\NormalTok{ join\_nearest[[}\StringTok{\textquotesingle{}ZCTA5\_left\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}distance\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}geometry\_left\textquotesingle{}}\NormalTok{]].groupby([}\StringTok{\textquotesingle{}ZCTA5\_left\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}geometry\_left\textquotesingle{}}\NormalTok{]).mean().reset\_index()}
\end{Highlighting}
\end{Shaded}

\hfill\break
b. An average distance of 8.9 miles from any zip code in Texas to the
nearest zip code with at least one hospital seems reasonable given the
state's unique geography. Texas is a large state with both densely
populated urban centers and vast rural areas, where hospitals are fewer
and farther apart.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Calculate total mean distance}
\BuiltInTok{print}\NormalTok{(}\StringTok{\textquotesingle{}The mean total distance is:\textquotesingle{}}\NormalTok{, mean\_distance\_zip[}\StringTok{\textquotesingle{}distance\textquotesingle{}}\NormalTok{].mean(), }\StringTok{\textquotesingle{}miles\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
The mean total distance is: 8.930919170416805 miles
\end{verbatim}

\hfill\break
c.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Plot mean distance by zipcode}
\NormalTok{mean\_distance\_zip }\OperatorTok{=}\NormalTok{ gpd.GeoDataFrame(mean\_distance\_zip, geometry}\OperatorTok{=}\StringTok{\textquotesingle{}geometry\_left\textquotesingle{}}\NormalTok{)}

\NormalTok{mean\_distance }\OperatorTok{=}\NormalTok{ mean\_distance\_zip.plot(column}\OperatorTok{=}\StringTok{\textquotesingle{}distance\textquotesingle{}}\NormalTok{, cmap}\OperatorTok{=}\StringTok{\textquotesingle{}Greens\textquotesingle{}}\NormalTok{, legend}\OperatorTok{=}\VariableTok{True}\NormalTok{)}
\NormalTok{plt.gcf().set\_size\_inches(}\DecValTok{8}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{mean\_distance.set\_title(}\StringTok{"Mean Distance (in miles) to Nearest Hospital by ZIP Code"}\NormalTok{, fontsize}\OperatorTok{=}\DecValTok{15}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-21-output-1.pdf}

\subsection{Effects of closures on access in Texas (15
pts)}\label{effects-of-closures-on-access-in-texas-15-pts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_corrected }\OperatorTok{=}\NormalTok{ df\_corrected[[}\StringTok{\textquotesingle{}FAC\_NAME\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Year of Susp. Closure\textquotesingle{}}\NormalTok{]]}

\CommentTok{\# Filter for Texas}
\NormalTok{texas\_closures }\OperatorTok{=}\NormalTok{ df\_corrected[(df\_corrected[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{\textgreater{}=} \DecValTok{75000}\NormalTok{) }\OperatorTok{\&}\NormalTok{ (df\_corrected[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{] }\OperatorTok{\textless{}=} \DecValTok{79900}\NormalTok{)]}

\CommentTok{\# Count closures by ZIP code}
\NormalTok{texas\_closures\_zip }\OperatorTok{=}\NormalTok{ texas\_closures.groupby(}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{).size().reset\_index(name}\OperatorTok{=}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{)}

\CommentTok{\# Summary table of the number of zipcodes vs. the number of closures they experienced}
\NormalTok{summary\_table }\OperatorTok{=}\NormalTok{ texas\_closures\_zip[}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{].value\_counts().reset\_index()}
\NormalTok{summary\_table.columns }\OperatorTok{=}\NormalTok{ [}\StringTok{\textquotesingle{}Number of Closures\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Number of ZIP Codes\textquotesingle{}}\NormalTok{]}
\NormalTok{summary\_table.style.hide()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{}\label{T_9ae67}\tabularnewline
\toprule\noalign{}
Number of Closures & Number of ZIP Codes \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Number of Closures & Number of ZIP Codes \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 32 \\
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  There are 32 directly affected zipcodes in Texas.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Merge shapefile with hospitals database 2016}
\NormalTok{closures\_texas }\OperatorTok{=}\NormalTok{ pd.merge(texas\_shp, texas\_closures\_zip, left\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{], right\_on}\OperatorTok{=}\NormalTok{[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{], how}\OperatorTok{=}\StringTok{\textquotesingle{}left\textquotesingle{}}\NormalTok{)}
\NormalTok{closures\_texas[}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ closures\_texas[}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{].fillna(}\DecValTok{0}\NormalTok{)}

\CommentTok{\#Create choropleth with closures by zipcode}
\NormalTok{closures\_texas\_plt }\OperatorTok{=}\NormalTok{ closures\_texas.plot(column}\OperatorTok{=}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{, cmap}\OperatorTok{=}\StringTok{\textquotesingle{}Reds\textquotesingle{}}\NormalTok{, legend}\OperatorTok{=}\VariableTok{True}\NormalTok{, edgecolor}\OperatorTok{=}\StringTok{\textquotesingle{}gray\textquotesingle{}}\NormalTok{, vmax}\OperatorTok{=}\DecValTok{1}\NormalTok{)}
\NormalTok{plt.gcf().set\_size\_inches(}\DecValTok{8}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{closures\_texas\_plt.set\_title(}\StringTok{"Number of Closures by ZIP Code"}\NormalTok{, fontsize}\OperatorTok{=}\DecValTok{15}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-23-output-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  There are 532 indirectly affected zipcodes in TX
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Filter directly affected zipcodes in TX}
\NormalTok{directly\_affected\_tx }\OperatorTok{=}\NormalTok{ closures\_texas[closures\_texas[}\StringTok{\textquotesingle{}closures\textquotesingle{}}\NormalTok{]}\OperatorTok{\textgreater{}}\DecValTok{0}\NormalTok{][[}\StringTok{\textquotesingle{}geometry\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]]}

\CommentTok{\#Create 10{-}mile buffer}
\NormalTok{directly\_affected\_tx[}\StringTok{\textquotesingle{}buffer\textquotesingle{}}\NormalTok{] }\OperatorTok{=}\NormalTok{ directly\_affected\_tx.geometry.}\BuiltInTok{buffer}\NormalTok{(}\DecValTok{10}\OperatorTok{/}\DecValTok{69}\NormalTok{)}

\CommentTok{\#Get indirectly affected zipcodes in TX}
\NormalTok{indirectly\_affected\_tx }\OperatorTok{=}\NormalTok{ gpd.sjoin(}
\NormalTok{    texas\_shp, directly\_affected\_tx.set\_geometry(}\StringTok{\textquotesingle{}buffer\textquotesingle{}}\NormalTok{), how}\OperatorTok{=}\StringTok{\textquotesingle{}inner\textquotesingle{}}\NormalTok{, predicate}\OperatorTok{=}\StringTok{\textquotesingle{}intersects\textquotesingle{}}\NormalTok{)}

\CommentTok{\#Remove directly affected zipcodes}
\NormalTok{indirectly\_affected\_tx }\OperatorTok{=}\NormalTok{ indirectly\_affected\_tx[}\OperatorTok{\textasciitilde{}}\NormalTok{indirectly\_affected\_tx[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].}\OperatorTok{\textbackslash{}}
\NormalTok{    isin(directly\_affected\_tx[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{])]}

\CommentTok{\#Find number of indirectly affected zip codes in TX}
\NormalTok{indirectly\_affected\_tx[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].nunique()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
532
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Create categories}
\NormalTok{texas\_shp[}\StringTok{\textquotesingle{}category\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \StringTok{\textquotesingle{}Not Affected\textquotesingle{}}
\NormalTok{texas\_shp.loc[texas\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].isin(directly\_affected\_tx[}\StringTok{\textquotesingle{}ZIP\_CD\textquotesingle{}}\NormalTok{]), }\StringTok{\textquotesingle{}category\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \StringTok{\textquotesingle{}Directly Affected\textquotesingle{}}
\NormalTok{texas\_shp.loc[texas\_shp[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{].isin(indirectly\_affected\_tx[}\StringTok{\textquotesingle{}ZCTA5\textquotesingle{}}\NormalTok{]), }\StringTok{\textquotesingle{}category\textquotesingle{}}\NormalTok{] }\OperatorTok{=} \StringTok{\textquotesingle{}Indirectly Affected\textquotesingle{}}

\CommentTok{\#Choropleth with categories}
\NormalTok{fig, ax }\OperatorTok{=}\NormalTok{ plt.subplots(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, figsize}\OperatorTok{=}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{8}\NormalTok{))}
\NormalTok{texas\_shp.plot(column}\OperatorTok{=}\StringTok{\textquotesingle{}category\textquotesingle{}}\NormalTok{, cmap}\OperatorTok{=}\StringTok{\textquotesingle{}coolwarm\textquotesingle{}}\NormalTok{, legend}\OperatorTok{=}\VariableTok{True}\NormalTok{, ax}\OperatorTok{=}\NormalTok{ax, }
\NormalTok{               legend\_kwds}\OperatorTok{=}\NormalTok{\{}\StringTok{\textquotesingle{}title\textquotesingle{}}\NormalTok{: }\StringTok{\textquotesingle{}Impact Category\textquotesingle{}}\NormalTok{\})}
\NormalTok{ax.set\_title(}\StringTok{"Impact of Hospital Closures on Texas ZIP Codes (2016{-}2019)"}\NormalTok{, fontsize}\OperatorTok{=}\DecValTok{15}\NormalTok{)}
\NormalTok{plt.show()}
\end{Highlighting}
\end{Shaded}

\includegraphics{pset4_template_files/figure-pdf/cell-25-output-1.pdf}

\subsection{Reflecting on the exercise (10
pts)}\label{reflecting-on-the-exercise-10-pts}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The ``first-pass'' method for identifying hospital closures in the
  data has several limitations that could lead to inaccurate
  interpretations. One major issue is that this method might mistake
  cases where hospitals have been absorbed into larger networks for
  example. In such situations, the hospital may still be serving the
  community, but the method categorizes it incorrectly as a permanent
  closure, thus distorting the analysis of actual healthcare access
  impacts.\\
  \strut \\
  On the other hand, the opposite could also occur: if a new hospital
  opens in the same zip code the year following a closure, this method
  might mistakenly interpret it as a ``reopening'' of the original
  hospital, when it is actually a new facility. This could underestimate
  the number of true closures and overestimate healthcare access
  continuity in certain areas.\\
  \strut \\
  To improve the accuracy of this analysis, I would suggest:\\
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Tracking location and name history: Checking for new facilities with
  similar names or close locations in subsequent years would help
  identify replacements rather than permanent closures.
\item
  Monitoring certification number changes: Since some hospitals change
  CMS certification numbers after mergers or acquisitions, tracking
  these changes alongside names and locations would help confirm whether
  the hospital continues to operate under new management.
\item
  Incorporating external data sources: Adding information from sources
  like the American Hospital Association or local health databases could
  verify whether a hospital is still operating, even under a different
  name or management, or if it has truly closed.
\item
  Analyzing opening and closing dates: Carefully examining each
  hospital's dates and other details, would help differentiate between
  new facilities and reopenings.
\end{itemize}




\end{document}
